// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATbVZ4TfgJHP83cJRFtHm-12T-YGEbWzE',
    appId: '1:1034585412397:web:e9546070dc1941626939a4',
    messagingSenderId: '1034585412397',
    projectId: 'tugas-akhir-bangunin',
    authDomain: 'tugas-akhir-bangunin.firebaseapp.com',
    storageBucket: 'tugas-akhir-bangunin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNSF3rZVrZxV4UwvhtvSoZGINAOEXb0Pg',
    appId: '1:1034585412397:android:98f781f491d916626939a4',
    messagingSenderId: '1034585412397',
    projectId: 'tugas-akhir-bangunin',
    storageBucket: 'tugas-akhir-bangunin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkC4lqxRbXTgbqOFAEnXGZs2yyUK_3aWE',
    appId: '1:1034585412397:ios:db96e582ced8c21e6939a4',
    messagingSenderId: '1034585412397',
    projectId: 'tugas-akhir-bangunin',
    storageBucket: 'tugas-akhir-bangunin.appspot.com',
    iosBundleId: 'com.example.bangunindFixedProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkC4lqxRbXTgbqOFAEnXGZs2yyUK_3aWE',
    appId: '1:1034585412397:ios:db96e582ced8c21e6939a4',
    messagingSenderId: '1034585412397',
    projectId: 'tugas-akhir-bangunin',
    storageBucket: 'tugas-akhir-bangunin.appspot.com',
    iosBundleId: 'com.example.bangunindFixedProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATbVZ4TfgJHP83cJRFtHm-12T-YGEbWzE',
    appId: '1:1034585412397:web:38fec8efc0c4571d6939a4',
    messagingSenderId: '1034585412397',
    projectId: 'tugas-akhir-bangunin',
    authDomain: 'tugas-akhir-bangunin.firebaseapp.com',
    storageBucket: 'tugas-akhir-bangunin.appspot.com',
  );

}